---
title: "master"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Delay TP main figures

This is a master script for the main figures in R.

```{r delaytp}
# load intertemporal choice trial data
load('../../data/all_trials_naivetp.RData')
# load follow-up and new group fits and data
load('../../data/delaytp.RData')
# load raw tpdata
timing <- read.csv(file = "../../data/timing_trials.csv")
tetp = subset(timing,te == 1)
tptp = subset(timing,te == 0)
# load R-squared for individual fits
load('../../data/real_r2.RData')
# load fitted draws for example subject
load('../../data/dfsubj.RData')
# load new posterior
load('../../data/new_posterior.RData')
```

## Fig. 2b

```{r fig2b, echo=FALSE}
source("fig2bsource.R")
fig2b(new_posterior)
```

## Fig. 2c

```{r fig2c, echo=FALSE}
source("fig2csource.R")
fig2c(naive_trials,newgr,nv_r2)
```

## Fig. 3ac

```{r fig3ac, echo=FALSE}
source("fig3source.R")
fig3(tetp,tptp,subj_te,subj_tp)
```

## Fig. 5ad

```{r fig5ad, echo=FALSE}
source("fig5source.R")
fig5(followup)
fig5(newgr)
table2S(followup)
table2L(followup)
table2S(newgr)
table2L(newgr)
```
